__title__ = "KonoPyUtil"
__description__ = "Python Utilities for Kono Analytics"
__url__ = "https://konoanalytics.com"
__version__ = "0.0.1"
__author__ = "Jonathan Bennett"
__author_email__ = "info@konoanalytics.com"
__license__ = "Apache 2.0"
__copyright__ = "Copyright 2022 Jonathan Bennett"
